# Our Gitlab CI is internal to Servall - see TravisCI file for public releases!

include:
 - project: 'meat-n-potatoes/ci'
   file: 'all.yml'
   ref: v1

stages:
  - lint
  - build
  - test
  - publish

lint:
  extends: .node-lint
  stage: lint

audit:
  extends: .node-audit
  stage: lint

build:
  extends: .node-build
  stage: build

test:
  extends: .node-test
  stage: test

publish:
  extends: .node-publish-tag
  stage: publish
